# Generated by Django 6.0.4 on 2026-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
