# Generated by Django 6.0.4 on 2026-06-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_bid_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='unread', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
