# Generated by Django 6.0.4 on 2026-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_notification_listing_notification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
